### ISSUE TITLE
How to run eval?

### ISSUE THREAD

**Issue by abisee** [shanzhenren/ClusType#2]
I'm trying to figure out how to run eval. From what I can tell, `run.sh` doesn't perform eval but there is code in `evaluation.py` that seems to be for evaluation. However, functions like `test_method` in `evaluation.py` aren't called anywhere else in the code. 

Could you provide some information about how to run evaluation? 

Thanks!

**Comment by shanzhenren** [comment]
@abisee , I updated the README to include the instruction on how to call `src/evaluation.py` to get the metrics. Several unused functions in `evaluation.py` has been cleaned up, including `test_method` as you pointed out. Hope it helps.
