### ISSUE TITLE
Incorrect SeedFile value

### ISSUE THREAD

**Issue by YangZhou0417** [shanzhenren/ClusType#4]
Hi, thanks for your research and all the work, I find the code quite useful for me to learn more about unsupervised NER!

There are two little issues that I want to address:

- In terms of the example run, I realize the correct value for **SeedFile** should be 'data/yelp/seed_yelp.txt' instead of 'result/yelp/seed_yelp.txt'. 

- I also don't think the notes in [this page](http://shanzhenren.github.io/ClusType/) is still valid. (However, I think the installation process in this page is really helpful)

**Comment by shanzhenren** [comment]
Thanks much @YangZhou0417 for pointing the typos and outdated github pages. We have corrected them. -- Xiang
