### ISSUE TITLE
FreeBase deprecated

### ISSUE THREAD

**Issue by YangZhou0417** [shanzhenren/ClusType#5]
As I'm trying the entity linking using dBpedia-Spotlight, I realize I can not do entity typing anymore as the FreeBase is deprecated.

More specifically, I can not find a good alternative to find "notable_types" now.
And the[ other APIs](https://stackoverflow.com/questions/32147848/query-wikidata-for-entity-types) does not seem to show good performance on entity typing: 

I would appreciate if you guys can provide some help on entity typing during seed entity generation.

Thanks.

**Comment by shanzhenren** [comment]
hi @YangZhou0417 , yes, the Freebase APIs are unaccessible now. Pls take a look at https://github.com/shanzhenren/StructMineDataPipeline for our in-house distant supervision module using Freebase dump (need to download to local).
